---
- name: Download Zabbix Agent for Ubuntu 14 amd64
get_url:
  url="http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix/zabbix-agent_3.0.11-1+trusty_amd64.deb"
  dest="/root"
when:
  - ansible_os_family == "Debian"
  - ansible_distribution == "Ubuntu"
  - ansible_distribution_major_version == "14"

- name: Download Zabbix Agent for Debian amd 64
get_url:
  url="http://repo.zabbix.com/zabbix/3.0/debian/pool/main/z/zabbix/zabbix-agent_3.0.11-1+jessie_amd64.deb"
  dest="/root"
when:
  - ansible_os_family == "Debian"
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version == "8"

- name: Download Zabbix Agent for Centos & RHEL 6 X86
get_url:
  url="http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-agent-3.0.11-1.el6.x86_64.rpm"
  dest="/root"
when:
  - ansible_os_family == "Redhat"
  - ansible_distribution_major_version == "6"
